apiVersion: v1
kind: Service
metadata:
  name: orderapp-svc
  labels:
    app: orderapp
spec:
  type: NodePort
  ports:
  - port: 8001 # The docker container port
    nodePort: 30001
    protocol: TCP
  selector:
    app: orderapp-ack