apiVersion: v1
kind: Service
metadata:
  name: personal-svc
  labels:
    app: personal
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8001 # Docker container port
  selector:
    app: personal-app
    