apiVersion: apps/v1
kind: Deployment
metadata:
  name: personal-app-deployment
  labels:
    app: personal
spec:
  replicas: 2
  minReadySeconds: 10
  selector:
    matchLabels:
      app: personal-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: personal-app
    spec:
      containers:
      - name: personal-app
        image: tombennett/personal:v3
        resources:
          limits:
            cpu: 600m
            memory: 256Mi
          requests:
            cpu: 200m
            memory: 128Mi
        ports:
          - containerPort: 8001
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /
            port: 8001
          initialDelaySeconds: 3
          periodSeconds: 15
        readinessProbe:
          httpGet:
            path: /
            port: 8001
          initialDelaySeconds: 10
          periodSeconds: 15
