apiVersion: v1
kind: Pod
metadata:
  name: orderapp-ack-pod
  labels:
    app: orderapp
spec:
  containers:
  - name: symf-app
    image: tombennett/api:latest
    volumeMounts:
      - name: log-storage
        mountPath: /data/logs
    ports:
    - containerPort: 8080
  volumes:
  - name: log-storage
    emptyDir: {}

#-
#
#apiVersion: v1
#kind: Pod
#metadata:
#  name: hello-pod
#  labels:
#    zone: prod
#    version: v1
#spec:
#  containers:
#  - name: hello-ctr
#    image: nigelpoulton/pluralsight-docker-ci:latest
#    ports:
#    - containerPort: 8080