apiVersion: v1
kind: Pod
metadata:
  name: orderapp-rabbit-pod
  labels:
    app: orderapp
spec:
  containers:
  - name: rabbit-mq
    image: rabbitmq
    volumeMounts:
      - name: log-storage
        mountPath: /data/logs
    ports:
    - containerPort: 5672
  volumes:
  - name: log-storage
    emptyDir: {}